- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - import_tasks: tasks/linux/core-setup.yaml
    - import_tasks: tasks/linux/tools-setup.yaml
    - import_tasks: tasks/linux/aws-setup.yaml
    - import_tasks: tasks/linux/docker-setup.yaml
    - import_tasks: tasks/linux/k8s-setup.yaml
    - import_tasks: tasks/linux/aws-setup.yaml
    - import_tasks: tasks/linux/zsh-setup.yaml
