- name: Install AWS CLI
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
  tags:
    - install
    - aws

- name: Install boto3
  ansible.buildin.pip:
    name: boto3
  tags:
    - install
    - aws

- name: Install AWS Systems Manager Plugin
  become: true
  shell: |
    curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
    dpkg -i session-manager-plugin.deb
    rm session-manager-plugin.deb
  tags:
    - install
    - aws
    - ssm