- name: AWS > Unzip CLI
  become: true
  ansible.builtin.unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: yes

- name: AWS > Install CLI
  become: true
  ansible.builtin.command: ./aws/install --update
  args:
    chdir: /tmp
  tags:
    - install
    - aws

- name: AWS > Install boto3
  ansible.builtin.pip:
    name: boto3
  tags:
    - install
    - aws

- name: AWS > Install Session Manager Plugin
  become: true
  shell: |
    curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
    dpkg -i session-manager-plugin.deb
    rm session-manager-plugin.deb
  tags:
    - install
    - aws
    - ssm
