- name: AWS > Install CLI
  become: true
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip -qq awscliv2.zip
    ./aws/install
    rm -rdf aws awscliv2.zip
  tags:
    - install
    - aws

- name: AWS > Install boto3
  ansible.builtin.pip:
    name: boto3
  tags:
    - install
    - aws

- name: AWS > Install Session Manager Plugin
  become: true
  shell: |
    curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
    dpkg -i session-manager-plugin.deb
    rm session-manager-plugin.deb
  tags:
    - install
    - aws
    - ssm
