- name: Install System Packages 1 (build-essential)
  become: true
  apt:
    name: ["build-essential"]
  tags:
    - install
    - core

- name: Install System Packages 2 (curl, wget, unzip, python3, python3-pip, vim)
  become: true
  apt:
    name: ["curl", "wget", "unzip", "python3", "python3-pip", "fzf", "tmux", "apt-transport-https", "ca-certificates", "vim"]
  tags:
    - install
    - core