- name: Core > Install System Packages 1 (build-essential)
  become: true
  apt:
    name: ["build-essential"]
  tags:
    - install
    - core

- name: Core > Install System Packages 2 (curl, wget, unzip, python3, python3-pip, vim)
  become: true
  apt:
    name: ["curl", "wget", "unzip", "python3", "python3-pip", "fzf", "tmux", "apt-transport-https", "ca-certificates", "vim"]
  tags:
    - install
    - core

- name: Core > Make /etc/apt/keyrings if it doesnt exist
  become: true
  shell: |
    if [ ! -d /etc/apt/keyrings ]; then
      mkdir -p -m 755 /etc/apt/keyrings
    fi
  tags:
    - install
    - core