- name: K8s > Install Kubectl
  become: true
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
    echo "$(<kubectl.sha256) kubectl" | sha256sum --check
    install -m 755 kubectl /usr/local/bin/kubectl
    rm kubectl kubectl.sha256
  tags:
    - install
    - k8s

- name: K8s > Install Helm
  become: true
  shell: |
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | tee /usr/share/keyrings/helm.gpg > /dev/null
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
    apt update
    apt install helm
  tags:
    - install
    - k8s
    - helm

- name: K8s > Install FluxCD CLI
  become: true
  shell: curl -s https://fluxcd.io/install.sh | bash
  tags:
    - install
    - k8s
    - fluxcd

- name: K8s > Install Kustomize
  become: true
  shell: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
  tags:
    - install
    - k8s
    - kustomize

- name: K8s > Install argocd-cli
  become: true
  shell: |
    curl -sSL -o /tmp/argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    install -m 555 /tmp/argocd-linux-amd64 /usr/local/bin/argocd
    rm /tmp/argocd-linux-amd64
  tags:
    - install
    - k8s
    - argocd

- name: K8s > Install krew
  shell: |
    (
      set -x; cd "$(mktemp -d)" &&
      OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
      ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
      KREW="krew-${OS}_${ARCH}" &&
      curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
      tar zxvf "${KREW}.tar.gz" &&
      ./"${KREW}" install krew
    )
  tags:
    - install
    - k8s
    - krew

- name: K8s > Install kubectl plugins (ctx, ns, tree, view-utilization)
  shell: |
    kubectl krew install ctx
    kubectl krew install ns
    kubectl krew install tree
    kubectl krew install view-utilization
  tags:
    - install
    - k8s
    - kubectl-plugins