- name: OpenTofu > Get Apt GPG Key
  ansible.builtin.get_url:
    url: https://get.opentofu.org/opentofu.gpg
    dest: /etc/apt/keyrings/opentofu.gpg
  tags:
    - install
    - terraform
    - opentofu
    - tofu

- name: OpenTofu Packages > Get Apt GPG Key
  ansible.builtin.get_url:
    url: https://packages.opentofu.org/opentofu/tofu/gpgkey
    dest: /etc/apt/keyrings/opentofu-repo.gpg
  tags:
    - install
    - terraform
    - opentofu
    - tofu

- name: OpenTofu > Add Binaries Apt Repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main"
    state: present
  tags:
    - install
    - terraform
    - opentofu
    - tofu

- name: Terraform > Add Source Apt Repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb-src [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main"
    state: present
  tags:
    - install
    - terraform
    - opentofu
    - tofu

- name: OpenTofu > Install Packages (tofu)
  become: true
  ansible.builtin.apt:
    name: tofu
    state: present
  tags:
    - install
    - terraform
    - opentofu
    - tofu