- name: Tools > Download Git-secrets
  ansible.builtin.git:
    repo: https://github.com/awslabs/git-secrets.git
    dest: /tmp/git-secrets
    version: master
  tags:
    - install
    - git-secrets
    - tools

- name: Tools > Install Git-secrets
  become: true
  ansible.builtin.command: make install
  args:
    chdir: /tmp/git-secrets
  tags:
    - install
    - git-secrets
    - tools

- name: Tools > gh-cli Apt Setup
  block:
    - name: github-cli | no apt key
      become: true
      ansible.builtin.get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg

    - name: github-cli | apt source
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        state: present
  tags: 
    - install
    - gh-cli
    - tools
    - github

- name: Tools > Install gh-cli
  become: true
  apt:
    name: ["gh"]
  tags: 
    - install
    - gh-cli
    - tools
    - github

- name: Tools > Download > NVM
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
    dest: /tmp/nvm-install.sh
  tags:
    - install
    - nvm
    - node
    - tools

- name: Tools > Install latest nodejs lts
  shell: |
    ./tmp/nvm-install.sh
    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
    nvm install --lts
  tags:
    - install
    - nvm
    - node
    - tools

- name: Tools > Node > Packages > Commitizen
  npm:
    name: commitizen
    global: yes
  tags:
    - install
    - node
    - tools

- name: Tools > Node > Packages > Conventional-Changelog
  npm:
    name: conventional-changelog
    global: yes
  tags:
    - install
    - node
    - tools


- name: Tools > Node > Packages > @digitalroute/cz-conventional-changelog-for-jira
  npm:
    name: '@digitalroute/cz-conventional-changelog-for-jira'
    global: yes
  tags:
    - install
    - node
    - tools


- name: Tools > Node > Packages > tldr
  npm:
    name: tldr
    global: yes
  tags:
    - install
    - node
    - tools
