- name: Tools > Download Git-secrets
  ansible.builtin.git:
    repo: https://github.com/awslabs/git-secrets.git
    dest: /tmp/git-secrets
  tags:
    - install
    - git-secrets
    - tools

- name: Tools > Install Git-secrets
  become: true
  shell: |
    cd /tmp/git-secrets
    make install
  tags:
    - install
    - git-secrets
    - tools

- name: Tools > Install gh-cli
  become: true
  shell: |
    wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
    &&  chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" |  tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    &&  apt update \
    &&  apt install gh -y
  tags: 
    - install
    - gh-cli
    - tools
    - github

- name: Tools > Install nvm
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  tags:
    - install
    - nvm
    - node
    - tools

- name: Tools > Install latest nodejs lts
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install --lts
  tags:
    - install
    - nvm
    - node
    - tools

- name: Tools > Install node packages (commitizen, conventional-changelog, @digitalroute/cz-conventional-changelog-for-jira, tldr)
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    npm install -g commitizen cz-conventional-changelog @digitalroute/cz-conventional-changelog-for-jira tldr
  tags:
    - install
    - nvm
    - node
    - tools
    - commitizen
    - tldr