- name: Install Systems Packages (zsh)
  become: true
  apt:
    name: ["zsh"]
  tags:
    - install
    - zsh
    - oh-my-zsh

- name: Check the Oh My Zsh doesn't exist
  stat:
    path: {{ ansible_env.HOME }}/.oh-my-zsh
  register: oh_my_stats
  tags:
    - install
    - zsh
    - oh-my-zsh

- name: Install Oh My Zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_stats.stat.exists == False
  tags:
    - install
    - zsh
    - oh-my-zsh

- name: Set default shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags:
    - install
    - zsh
    - oh-my-zsh

- name: Install oh-my-zsh plugins (zsh-autosuggestions)
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - zsh
    - oh-my-zsh
    - zsh-autosuggestions
    